version: '3'
services:
  mage:
    image: mageai/mageai:latest
    ports:
      - 6789:6789
    volumes:
      - ./mage_data:/home/src
      - ./mage_data/gcp_credentials.json:/home/src/gcp_credentials.json
    restart: always
