name: 'dbt_airbnb_project'
version: '1.0.0'

profile: 'dbt_airbnb_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_airbnb_project:
    +materialized: table
