version: 0.1.1

default:
  # MongoDB
  MONGODB_CONNECTION_STRING: "mongodb+srv://thallys:s6vwJqdOTYywumzw@cluster0.ye06e.mongodb.net/sample_airbnb?retryWrites=true&w=majority&appName=Cluster0"
  MONGODB_DATABASE: sample_airbnb
  MONGODB_COLLECTION: listingsAndReviews

  # BigQuery
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: /home/src/gcp_credentials.json
  GOOGLE_PROJECT_ID: mage-airbnb-pipeline
