version: 0.1.1
default:
  MONGODB_CONNECTION_STRING: "mongodb+srv://thallys:s6vwJqdOTYywumzw@cluster0.ye06e.mongodb.net/sample_airbnb?retryWrites=true&w=majority&appName=Cluster0"
  MONGODB_DATABASE: sample_airbnb
  MONGODB_COLLECTION: listingsAndReviews
