name: Mage CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare GCP credentials
        run: |
          mkdir -p mage_data
          cat << 'EOF' > mage_data/gcp_credentials.json
          ${{ secrets.GCP_CREDENTIALS_JSON }}
          EOF
          chmod 600 mage_data/gcp_credentials.json

      - name: Start Mage container
        run: docker compose up -d

      - name: Wait for Mage API
        run: |
          for i in $(seq 1 10); do
            curl --fail http://localhost:6789/health && break
            sleep 3
          done

      - name: Run Mage pipeline
        run: |
          docker compose exec mage mage run /home/src/default_repo ingest_airbnb_mongo
